# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gts3llte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gts3llte/proprietary/bin/ipacm-diag:system/bin/ipacm-diag \
    vendor/samsung/gts3llte/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/gts3llte/proprietary/bin/pm-proxy:system/bin/pm-proxy \
    vendor/samsung/gts3llte/proprietary/bin/pm-service:system/bin/pm-service \
    vendor/samsung/gts3llte/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/gts3llte/proprietary/bin/radish:system/bin/radish \
    vendor/samsung/gts3llte/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/gts3llte/proprietary/bin/tftp_server:system/bin/tftp_server \
    vendor/samsung/gts3llte/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    vendor/samsung/gts3llte/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    vendor/samsung/gts3llte/proprietary/etc/data/qmi_config.xml:system/etc/data/qmi_config.xml \
    vendor/samsung/gts3llte/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/gts3llte/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/gts3llte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/gts3llte/proprietary/lib64/libfloatingfeature.so:system/lib64/libfloatingfeature.so \
    vendor/samsung/gts3llte/proprietary/lib64/libril.so:system/lib64/libril.so \
    vendor/samsung/gts3llte/proprietary/lib64/libsec-ril.so:system/lib64/libsec-ril.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libqcmaputils.so:system/vendor/lib/libqcmaputils.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libqcmaputils.so:system/vendor/lib64/libqcmaputils.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so
