# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gts3llte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gts3llte/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/gts3llte/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/gts3llte/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/gts3llte/proprietary/bin/radish:system/bin/radish \
    vendor/samsung/gts3llte/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/gts3llte/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/gts3llte/proprietary/bin/tftp_server:system/bin/tftp_server \
    vendor/samsung/gts3llte/proprietary/framework/telephony-common.jar:system/framework/telephony-common.jar \
    vendor/samsung/gts3llte/proprietary/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
    #vendor/samsung/gts3llte/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/gts3llte/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/gts3llte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/gts3llte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/gts3llte/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/gts3llte/proprietary/lib/libxml2.so:system/lib/libxml2.so \
    vendor/samsung/gts3llte/proprietary/lib64/libprotobuf-cpp-full.so:system/lib64/libprotobuf-cpp-full.so \
    #vendor/samsung/gts3llte/proprietary/lib64/libreference-ril.so:system/lib64/libreference-ril.so \
    vendor/samsung/gts3llte/proprietary/lib64/libril.so:system/lib64/libril.so \
    vendor/samsung/gts3llte/proprietary/lib64/librilutils.so:system/lib64/librilutils.so \
    vendor/samsung/gts3llte/proprietary/lib64/libsec-ril.so:system/lib64/libsec-ril.so \
    vendor/samsung/gts3llte/proprietary/lib64/libsecnativefeature.so:system/lib64/libsecnativefeature.so \
    vendor/samsung/gts3llte/proprietary/lib64/libsecril-client.so:system/lib64/libsecril-client.so \
    vendor/samsung/gts3llte/proprietary/lib64/libxml2.so:system/lib64/libxml2.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libqcmaputils.so:system/vendor/lib/libqcmaputils.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libqcmaputils.so:system/vendor/lib64/libqcmaputils.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    vendor/samsung/gts3llte/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so

PRODUCT_PACKAGES += \
    libril
